# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    steam_api_key: '%env(STEAM_API_KEY)%'
    steam_id: '%env(STEAM_ID)%'
    app_password: '%env(APP_PASSWORD)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\SteamApiService:
        arguments:
            $apiKey: '%steam_api_key%'

    App\Service\UserTokenService:
        arguments:
            $appEnv: '%kernel.environment%'

    App\Command\SteamFindGameCommand:
        arguments:
            $steamId: '%steam_id%'

    App\Controller\LoginController:
        arguments:
            $appPassword: '%app_password%'
            $steamId: '%steam_id%'

    App\Controller\SteamAuthController:
        arguments:
            $inviteToken: '%env(default::FRIEND_INVITE_TOKEN)%'
